config/routes.rb
Rails.application.routes.draw do
  get '/base/:action' => 'base'

  get '/forums/recent' => 'sb_posts#index', :as => :recent_forum_posts
  get '/photos/recent' => 'photos#recent', :as => :recent_photos

  resources :authorizations
  get '/auth/:provider/callback' => 'authorizations#create', :as => :callback
  get '/auth/failure' => 'authorizations#failure'

  resources :sb_posts, :as => 'all_sb_posts' do
    collection do
      get :search
      get :monitored
    end
  end

  resources :monitorship
  resources :sb_posts do
    collection do
      get :search
      get :monitored
    end
  end

  resources :forums do
    resources :sb_posts

    resources :moderators
    resources :topics do
      resources :sb_posts
      resource :monitorship
    end
  end

  get '/forums' => 'forums#index', :as => :forum_home

  get 'sitemap.xml' => 'sitemap#index', :format => 'xml'
  get 'sitemap' => 'sitemap#index'

  get '/' => 'base#site_index', :as => :home

  scope "/admin" do
    get 'dashboard' => 'homepage_features#index', :as => :admin_dashboard
    match 'users' => 'admin#users', :as => :admin_users, :via => [:post, :get]
    get 'messages' => 'admin#messages', :as => :admin_messages
    match 'comments' => 'admin#comments', :as => :admin_comments, :via => [:post, :get]
    match 'tags' => 'tags#manage', :as => :admin_tags, :via => [:post, :get]
    get 'events' => 'admin#events', :as => :admin_events
    get 'clear_cache' => 'admin#clear_cache', :as => :admin_clear_cache
    get 'subscribers(.:format)' => "admin#subscribers", :as => :admin_subscribers
    get 'activate_user' => "admin#activate_user", :as => :admin_activate_user
    get 'deactivate_user' => 'admin#deactivate_user', :as => :admin_deactivate_user

    resources :pages, :as => :admin_pages do
      member do
        get :preview
      end
    end
  end

  get 'pages/:id' => 'pages#show', :as => :pages


  get '/login' => 'sessions#new', :as => :login
  get '/signup' => 'users#new', :as => :signup
  get '/logout' => 'sessions#destroy', :as => :logout

  get '/signup/:inviter_id/:inviter_code' => 'users#new', :as => :signup_by_id
  get '/forgot_password' => 'password_resets#new', :as => :forgot_password
  resources :password_resets

  match '/forgot_username' => 'users#forgot_username', :as => :forgot_username, :via => [:get, :post]

  post '/resend_activation' => 'users#resend_activation', :as => :resend_activation

  get '/new_clipping' => 'clippings#new_clipping'
  post '/load_images_from_uri' => 'clippings#load_images_from_uri', :format => 'js'
  get '/clippings(/page/:page)' => 'clippings#site_index', :as => :site_clippings
  get '/clippings.rss' => 'clippings#site_index', :as => :rss_site_clippings, :format => 'rss'

  get '/featured(/page/:page)' => 'posts#featured', :as => :featured
  get '/featured.rss' => 'posts#featured', :as => :featured_rss, :format => 'rss'
  get '/popular(/page/:page)' => 'posts#popular', :as => :popular
  get '/popular.rss' => 'posts#popular', :as => :popular_rss, :format => 'rss'
  get '/recent(/page/:page)' => 'posts#recent', :as => :recent
  get '/recent.rss' => 'posts#recent', :as => :recent_rss, :format => 'rss'
  get '/rss' => 'base#rss_site_index', :as => :rss_redirect
  get '/site_index.rss' => 'base#site_index', :as => :rss, :format => 'rss'
  get '/advertise' => 'base#advertise', :as => :advertise
  get '/css_help' => 'base#css_help', :as => :css_help
  get '/about' => 'base#about', :as => :about
  get '/faq' => 'base#faq', :as => :faq
  get '/footer_content' => 'base#footer_content', :as => :footer_content

  get '/account/edit' => 'users#edit_account', :as => :edit_account_from_email

  get '/friendships.xml' => 'friendships#index', :as => :friendships_xml, :format => 'xml'
  get '/friendships' => 'friendships#index', :as => :friendships

  get 'manage_photos' => 'photos#manage_photos', :as => :manage_photos
  post 'create_photo.js' => 'photos#create', :as => :create_photo, :format => 'js'

  resources :sessions
  resources :statistics do
    collection do
      get :activities
      get :activities_chart
    end
  end

  resources :tags do
    get :auto_complete_for_tag_name, :on => :collection
  end
  get '/tags/:id/:type' => 'tags#show', :as => :show_tag_type
  get '/search/tags' => 'tags#show', :as => :search_tags

  resources :categories
  post '/categories/show_tips' => 'categories#show_tips', :as => :categories_show_tips

  resources :events do
    get 'page/:page', :action => :index, :on => :collection
    collection do
      get :past
      get :ical
    end
    member do
      get :clone
    end
    resources :rsvps
  end
  scope "/:commentable_type/:commentable_id" do
    resources :comments, :as => :commentable_comments do
      member do
        get :unsubscribe
        put :approve
      end
    end
  end
  resources :comments do
    collection do
      delete :delete_selected
    end
  end
  resources :comments

  resources :homepage_features
  resources :metro_areas
  resources :ads

  resources :activities

  resources :users do

    get 'page/:page', :action => :index, :on => :collection

    collection do
      post 'return_admin'
      delete 'delete_selected'
    end
    member do
      get 'dashboard'
      get 'edit_account'
      get 'invite'
      get 'signup_completed'
      get 'activate'

      patch 'toggle_moderator'
      patch 'toggle_featured'

      patch 'change_profile_photo'
      patch 'update_account'
      patch 'deactivate'

      get 'welcome_photo'
      get 'welcome_about'
      get 'welcome_invite'
      get 'welcome_complete'

      post 'assume'

      get 'statistics'
      match 'crop_profile_photo', :via => [:get, :put, :patch]
      match 'upload_profile_photo', :via => [:get, :put, :patch]
      patch 'upload_profile_photo'
    end

    resources :friendships do
      collection do
        get :accepted
        get :pending
        get :denied
      end
      member do
        patch :accept
        patch :deny
      end
    end

    resources :photos do
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :posts do
      get 'page/:page', :action => :index, :on => :collection

      collection do
        # get 'manage(/page/:page)', :action => :manage
        match :manage, :via => [:get, :post]
      end

      member do
        post :send_to_friend
        patch :update_views
        get :category_tips_update
        get :preview
      end
    end

    resources :clippings

    resources :activities do
      get 'page/:page', :action => :index, :on => :collection
      collection do
        get :network
      end
    end

    resources :invitations

    resources :favorites
    resources :messages do
      post :auto_complete_for_username, :on => :collection
      collection do
        post :delete_message_threads
        post :delete_selected

      end
    end

    resources :comments
    resources :photo_manager

    resources :albums do
      resources :photos do
        collection do
          post :swfupload
          get :slideshow
        end
      end
    end

  end

  scope '/:favoritable_type/:favoritable_id' do
    resources :favorites
  end

  resources :votes
  resources :invitations
  get '/users/:user_id/posts/category/:category_name' => 'posts#index', :as => :users_posts_in_category
  post '/users/metro_area_update' => 'users#metro_area_update', :as => :users_metro_area_update

end

app/views/admin/comments.html.haml
-@page_title = 'Comments'
= render :partial => 'shared/admin_nav'

= bootstrap_form_for @search, :url => admin_comments_path, :html => {:class => "form form-horizontal"} do |f|
  %h2=:search.l
  = f.text_field :author_email_or_user_email_cont, :label => :email.l

  .controls= f.submit :search.l

= form_tag delete_selected_comments_path, :method => :delete, :id => 'comments' do
  %table.table.table-bordered.table-striped
    %tr
      %th=:delete.l
      %th=:author.l
      %th{:width => "50%"}=:body_text.l
      %th=:on_commentable.l
      %th=:actions.l
    - @comments.each do |comment|
      %tr{:id => "comment-#{comment.id}"}
        %td= check_box_tag "delete[]", comment.id
        %td
          .left
            -if comment.user
              = link_to h(comment.user.login), user_path(comment.user)
              %br
              %small= comment.user.email
            -else
              = link_to_unless(comment.author_url.blank?, h(comment.username), h(comment.author_url)){ h(comment.username) }
              %br
              %small=comment.author_email
              %br
              %small="(#{comment.author_url})"
        %td{:style => 'overflow:hidden;'}
          = comment.comment.html_safe
        %td
          -if comment.commentable_name.blank?
            =link_to comment.commentable_type, commentable_url(comment)
          -else
            =link_to comment.commentable_name, commentable_url(comment)
        %td
          =link_to :delete.l, commentable_comment_path(comment.commentable_type, comment.commentable_id, comment), :method => :delete, 'data-manual-confirm' => "Are you sure you want to permanently delete this comment", :class => 'btn btn-danger delete-via-ajax', 'data-target' => "comment_#{comment.id}"
  -if @comments.any?
    %p
      %a.btn{:href=>"#", :onclick=>"checkboxes.each(function(e){ e.checked = (e.checked == 0 ? 1 : 0) }); return false;"} Toggle all
      = submit_tag :delete_selected.l, :class => 'btn btn-danger'

= paginate @comments, :theme => 'bootstrap'

-content_for :end_javascript do
  :javascript
    var form = $('comments');
    checkboxes = form.getInputs('checkbox');

app/views/admin/events.html.haml
= render :partial => 'shared/admin_nav'
-@page_title = :events.l

%table.table.table-bordered.table-striped
  %tr
    %th=:name.l
    %th=:metro_area.l
    %th=:when.l
    %th=:actions.l

  - for event in @events
    %tr
      %td= event.name
      %td= event.try(:metro_area).try(:name)
      %td=h event.time_and_date
      %td
        = link_to :show.l, event_path(event), :class => 'btn'
        = link_to :clone.l, clone_event_path(event), :class => 'btn btn-success'
        = link_to :edit.l, edit_event_path(event), :class => 'btn btn-warning'
        = link_to :delete.l, event_path(event), data: { confirm: :are_you_sure.l }, :method => :delete, :class => 'btn btn-danger'

=paginate @events, :theme => 'bootstrap'

%p= link_to :new_event.l, new_event_path, :class => 'btn btn-success'

app/views/admin/messages.html.haml
-@page_title = :sent_messages.l
= render :partial => 'shared/admin_nav'
= render :partial => "messages/sent"

app/views/admin/update.js.erb
alert('This should not happen');

app/views/admin/users.html.haml
= render :partial => 'shared/admin_nav'
-@page_title = :members.l
-box do
  = form_tag admin_users_url, :class => 'MainForm', :method => :get do
    %label= :user_login.l
    = text_field_tag 'login', params['login']
    %label= :user_e_mail.l
    = text_field_tag 'email', params['email']
    %p
      %input{:type=>"submit", :value=> :search_users.l, :class => 'btn' }

    = paginate @users, :theme => 'bootstrap'

  = form_tag delete_selected_users_path, :id => 'users' do
    %table{"cellspacing"=>"0", "border"=>"0", "cellpadding"=>"0", "width"=>"100%"}
      %tr
        %th
        %th
        %th
        %th
        %th=:login.l
        %th=:e_mail.l
        %th=:status.l
        %th=:actions.l

      - @users.each do |user|
        %tr{:id => "user_#{user.id}"}
          %td
            = link_to '<i class="icon-trash"></i>'.html_safe, user_path(user), :method => :delete, 'data-manual-confirm' => "Are you sure you want to permanently delete this user", :class => 'delete-via-ajax'                                                                     
          %td
            -if !configatron.akismet_key.nil?                
              = link_to image_tag('icons/bad-flag.png'), user_path(user, :spam => true), :method => :delete, :confirm => "Are you sure you want to permanently delete this user and mark it as spam!?", :class => 'delete-via-ajax'                                             
          %td= check_box_tag "delete[]", user.id
          
          %td
            -if user.avatar
              = image_tag user.avatar.photo.url(:thumb), :width => 25
          %td
            = link_to h(user.login), user_path(user)
          %td
            = h user.email
          %td
            = user.active? ? :active.l : :inactive.l
          %td
            = link_to :assume_id.l , assume_user_path(user), :method => 'post', :class => 'btn'
            -unless user.active?
              = link_to :activate.l, admin_activate_user_path(user), :class => 'btn btn-success'

    -if @users.any?         
      -if !configatron.akismet_key.nil?
        = check_box_tag :spam
        =:delete_selected_mark_as_spam.l
        %br
      %a.btn.check-all{:href=>"#"} Toggle all     
      = submit_tag :delete_selected.l, :class => 'btn btn-danger'

    = paginate @users, :theme => 'bootstrap'