config/routes.rb
Rails.application.routes.draw do
  get '/base/:action' => 'base'

  get '/forums/recent' => 'sb_posts#index', :as => :recent_forum_posts
  get '/photos/recent' => 'photos#recent', :as => :recent_photos

  resources :authorizations
  get '/auth/:provider/callback' => 'authorizations#create', :as => :callback
  get '/auth/failure' => 'authorizations#failure'

  resources :sb_posts, :as => 'all_sb_posts' do
    collection do
      get :search
      get :monitored
    end
  end

  resources :monitorship
  resources :sb_posts do
    collection do
      get :search
      get :monitored
    end
  end

  resources :forums do
    resources :sb_posts

    resources :moderators
    resources :topics do
      resources :sb_posts
      resource :monitorship
    end
  end

  get '/forums' => 'forums#index', :as => :forum_home

  get 'sitemap.xml' => 'sitemap#index', :format => 'xml'
  get 'sitemap' => 'sitemap#index'

  get '/' => 'base#site_index', :as => :home

  scope "/admin" do
    get 'dashboard' => 'homepage_features#index', :as => :admin_dashboard
    match 'users' => 'admin#users', :as => :admin_users, :via => [:post, :get]
    get 'messages' => 'admin#messages', :as => :admin_messages
    match 'comments' => 'admin#comments', :as => :admin_comments, :via => [:post, :get]
    match 'tags' => 'tags#manage', :as => :admin_tags, :via => [:post, :get]
    get 'events' => 'admin#events', :as => :admin_events
    get 'clear_cache' => 'admin#clear_cache', :as => :admin_clear_cache
    get 'subscribers(.:format)' => "admin#subscribers", :as => :admin_subscribers
    get 'activate_user' => "admin#activate_user", :as => :admin_activate_user
    get 'deactivate_user' => 'admin#deactivate_user', :as => :admin_deactivate_user

    resources :pages, :as => :admin_pages do
      member do
        get :preview
      end
    end
  end

  get 'pages/:id' => 'pages#show', :as => :pages


  get '/login' => 'sessions#new', :as => :login
  get '/signup' => 'users#new', :as => :signup
  get '/logout' => 'sessions#destroy', :as => :logout

  get '/signup/:inviter_id/:inviter_code' => 'users#new', :as => :signup_by_id
  get '/forgot_password' => 'password_resets#new', :as => :forgot_password
  resources :password_resets

  match '/forgot_username' => 'users#forgot_username', :as => :forgot_username, :via => [:get, :post]

  post '/resend_activation' => 'users#resend_activation', :as => :resend_activation

  get '/new_clipping' => 'clippings#new_clipping'
  post '/load_images_from_uri' => 'clippings#load_images_from_uri', :format => 'js'
  get '/clippings(/page/:page)' => 'clippings#site_index', :as => :site_clippings
  get '/clippings.rss' => 'clippings#site_index', :as => :rss_site_clippings, :format => 'rss'

  get '/featured(/page/:page)' => 'posts#featured', :as => :featured
  get '/featured.rss' => 'posts#featured', :as => :featured_rss, :format => 'rss'
  get '/popular(/page/:page)' => 'posts#popular', :as => :popular
  get '/popular.rss' => 'posts#popular', :as => :popular_rss, :format => 'rss'
  get '/recent(/page/:page)' => 'posts#recent', :as => :recent
  get '/recent.rss' => 'posts#recent', :as => :recent_rss, :format => 'rss'
  get '/rss' => 'base#rss_site_index', :as => :rss_redirect
  get '/site_index.rss' => 'base#site_index', :as => :rss, :format => 'rss'
  get '/advertise' => 'base#advertise', :as => :advertise
  get '/css_help' => 'base#css_help', :as => :css_help
  get '/about' => 'base#about', :as => :about
  get '/faq' => 'base#faq', :as => :faq
  get '/footer_content' => 'base#footer_content', :as => :footer_content

  get '/account/edit' => 'users#edit_account', :as => :edit_account_from_email

  get '/friendships.xml' => 'friendships#index', :as => :friendships_xml, :format => 'xml'
  get '/friendships' => 'friendships#index', :as => :friendships

  get 'manage_photos' => 'photos#manage_photos', :as => :manage_photos
  post 'create_photo.js' => 'photos#create', :as => :create_photo, :format => 'js'

  resources :sessions
  resources :statistics do
    collection do
      get :activities
      get :activities_chart
    end
  end

  resources :tags do
    get :auto_complete_for_tag_name, :on => :collection
  end
  get '/tags/:id/:type' => 'tags#show', :as => :show_tag_type
  get '/search/tags' => 'tags#show', :as => :search_tags

  resources :categories
  post '/categories/show_tips' => 'categories#show_tips', :as => :categories_show_tips

  resources :events do
    get 'page/:page', :action => :index, :on => :collection
    collection do
      get :past
      get :ical
    end
    member do
      get :clone
    end
    resources :rsvps
  end
  scope "/:commentable_type/:commentable_id" do
    resources :comments, :as => :commentable_comments do
      member do
        get :unsubscribe
        put :approve
      end
    end
  end
  resources :comments do
    collection do
      delete :delete_selected
    end
  end
  resources :comments

  resources :homepage_features
  resources :metro_areas
  resources :ads

  resources :activities

  resources :users do

    get 'page/:page', :action => :index, :on => :collection

    collection do
      post 'return_admin'
      delete 'delete_selected'
    end
    member do
      get 'dashboard'
      get 'edit_account'
      get 'invite'
      get 'signup_completed'
      get 'activate'

      patch 'toggle_moderator'
      patch 'toggle_featured'

      patch 'change_profile_photo'
      patch 'update_account'
      patch 'deactivate'

      get 'welcome_photo'
      get 'welcome_about'
      get 'welcome_invite'
      get 'welcome_complete'

      post 'assume'

      get 'statistics'
      match 'crop_profile_photo', :via => [:get, :put, :patch]
      match 'upload_profile_photo', :via => [:get, :put, :patch]
      patch 'upload_profile_photo'
    end

    resources :friendships do
      collection do
        get :accepted
        get :pending
        get :denied
      end
      member do
        patch :accept
        patch :deny
      end
    end

    resources :photos do
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :posts do
      get 'page/:page', :action => :index, :on => :collection

      collection do
        # get 'manage(/page/:page)', :action => :manage
        match :manage, :via => [:get, :post]
      end

      member do
        post :send_to_friend
        patch :update_views
        get :category_tips_update
        get :preview
      end
    end

    resources :clippings

    resources :activities do
      get 'page/:page', :action => :index, :on => :collection
      collection do
        get :network
      end
    end

    resources :invitations

    resources :favorites
    resources :messages do
      post :auto_complete_for_username, :on => :collection
      collection do
        post :delete_message_threads
        post :delete_selected

      end
    end

    resources :comments
    resources :photo_manager

    resources :albums do
      resources :photos do
        collection do
          post :swfupload
          get :slideshow
        end
      end
    end

  end

  scope '/:favoritable_type/:favoritable_id' do
    resources :favorites
  end

  resources :votes
  resources :invitations
  get '/users/:user_id/posts/category/:category_name' => 'posts#index', :as => :users_posts_in_category
  post '/users/metro_area_update' => 'users#metro_area_update', :as => :users_metro_area_update

end

app/models/acts_as_taggable_on/tag.rb
#require_dependency ActsAsTaggableOn::Engine.config.root.join('app', 'models', 'acts_as_taggable_on', 'tag.rb').to_s

class ActsAsTaggableOn::Tag < ActiveRecord::Base

  class << self
    def popular(limit = 20, type = nil)
      tags = ActsAsTaggableOn::Tag.counts(:at_least => 0).limit(limit).order('count DESC')
      tags = tags.where("taggings.taggable_type = ?", type.capitalize) if type
      tags
    end

    def default_per_page
      25
    end

    # Calculate the tag counts for all tags.
    #
    # - +:start_at+ - restrict the tags to those created after a certain time
    # - +:end_at+   - restrict the tags to those created before a certain time
    # - +:at_least+ - exclude tags with a frequency less than the given value
    # - +:at_most+  - exclude tags with a frequency greater than the given value
    #
    # Deprecated:
    #
    # - +:conditions+
    # - +:limit+
    # - +:order+
    #
    def counts(options = {})
      options.assert_valid_keys :start_at, :end_at, :at_least, :at_most, :conditions, :limit, :order, :joins

      tags = select("#{quoted_table_name}.id", "#{quoted_table_name}.name", "COUNT(#{quoted_table_name}.id) AS count")
      tags = tags.joins(:taggings)
      tags = tags.having(["COUNT(#{ActsAsTaggableOn::Tagging.quoted_table_name}.id) >= ?", options[:at_least]]) if options[:at_least]
      tags = tags.having(["COUNT(#{ActsAsTaggableOn::Tagging.quoted_table_name}.id) <= ?", options[:at_most]])  if options[:at_most]
      tags = tags.where("#{ActsAsTaggableOn::Tagging.quoted_table_name}.created_at >= ?", options[:start_at]) if options[:start_at]
      tags = tags.where("#{ActsAsTaggableOn::Tagging.quoted_table_name}.created_at <= ?", options[:end_at])   if options[:end_at]
      tags = tags.where(options[:conditions]) if options[:conditions]
      tags = tags.limit(options[:limit])      if options[:limit]
      tags = tags.order(options[:order])      if options[:order]

      if joins = options.delete(:joins)
        tags = tags.joins(joins)
      end

      tags.group("#{quoted_table_name}.id, #{quoted_table_name}.name")
    end


  end

  def to_param
    URI.escape(URI.escape(self.name), /[\/.?#]/)
  end

  def related_tags(limit = 10)
    taggables = self.taggings.limit(10).to_a.collect{|t| t.taggable }.compact

    tagging_ids = taggables.map{|t| t.taggings.limit(10).map(&:id) }.flatten.uniq
    return [] if tagging_ids.blank?

    ActsAsTaggableOn::Tag.where("tags.id != '#{self.id}'")
      .select("tags.id, tags.name, COUNT(tags.id) as count")
      .joins(:taggings)
      .where({:taggings => {:id => tagging_ids }})
      .group("tags.id, tags.name")
      .order("count DESC")
      .limit(limit)
  end

end

app/controllers/tags_controller.rb
class TagsController < BaseController
  before_filter :login_required, :only => [:manage, :edit, :update, :destroy]
  before_filter :admin_required, :only => [:manage, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => 'auto_complete_for_tag_name'

  caches_action :show, :cache_path => Proc.new { |controller| controller.send(:tag_url, controller.params[:id]) }, :if => Proc.new{|c| c.cache_action? }
  def cache_action?
    !logged_in? && params[:type].blank?
  end

  def auto_complete_for_tag_name
    @tags = ActsAsTaggableOn::Tag.all
    @tag_names = []
    for tag in @tags
      @tag_names << tag.name
    end
    respond_to do |format|
      format.json {render :inline => @tag_names.to_json}
    end
  end

  def index
    @tags = popular_tags(100).to_a

    @user_tags = popular_tags(75, 'User').to_a

    @post_tags = popular_tags(75, 'Post').to_a

    @photo_tags = popular_tags(75, 'Photo').to_a

    @clipping_tags = popular_tags(75, 'Clipping').to_a
  end

  def manage
    @search = ActsAsTaggableOn::Tag.search(params[:q])
    @tags = @search.result
    @tags = @tags.order('name ASC').distinct.page(params[:page]).per(100)
  end


  def edit
    @tag = ActsAsTaggableOn::Tag.find_by_name(URI::decode(params[:id]))
  end

  def update
    @tag = ActsAsTaggableOn::Tag.find_by_name(URI::decode(params[:id]))

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        flash[:notice] = :tag_was_successfully_updated.l
        format.html { redirect_to admin_tags_url }
        format.xml  { render :nothing => true }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors.to_xml }
      end
    end
  end

  def destroy
    @tag = ActsAsTaggableOn::Tag.find_by_name(URI::decode(params[:id]))
    @tag.destroy

    respond_to do |format|
      format.html {
        flash[:notice] = :tag_was_successfully_deleted.l
        redirect_to admin_tags_url
      }
      format.xml  { render :nothing => true }
    end
  end

  def show
    tag_array = ActsAsTaggableOn::TagList.from( URI::decode(params[:id]) )

    @tags = ActsAsTaggableOn::Tag.where('name IN (?)', tag_array)
    if @tags.nil? || @tags.empty?
      flash[:notice] = :tag_does_not_exists.l_with_args(:tag => tag_array)
      redirect_to :action => :index and return
    end
    @related_tags = @tags.first.related_tags
    @tags_raw = @tags.collect { |t| t.name } .join(',')

    if params[:type]
      case params[:type]
        when 'Post', 'posts'
          @pages = @posts = Post.recent.tagged_with(tag_array).page(params[:page]).per(20)
          @photos, @users, @clippings = [], [], []
        when 'Photo', 'photos'
          @pages = @photos = Photo.recent.tagged_with(tag_array).page(params[:page]).per(30)
          @posts, @users, @clippings = [], [], []
        when 'User', 'users'
          @pages = @users = User.recent.tagged_with(tag_array).page(params[:page]).per(30)
          @posts, @photos, @clippings = [], [], []
        when 'Clipping', 'clippings'
          @pages = @clippings = Clipping.recent.tagged_with(tag_array).page(params[:page]).per(10)
          @posts, @photos, @users = [], [], []
      else
        @clippings, @posts, @photos, @users = [], [], [], []
      end
    else
      @posts      = Post.recent.limit(5).tagged_with(tag_array)
      @photos     = Photo.recent.limit(10).tagged_with(tag_array)
      @users      = User.recent.limit(10).tagged_with(tag_array)
      @clippings  = Clipping.recent.limit(10).tagged_with(tag_array)
    end
  end

end

app/views/tags/edit.html.haml
-@page_title=:editing_tag.l
= render :partial => 'shared/admin_nav'

%p
  =link_to :back.l, admin_tags_path, :class => 'btn'
  =link_to :show.l, tag_path(@tag), :class => 'btn'
  =link_to :delete.l, tag_path(@tag), :method => 'delete', data: { confirm: :are_you_sure.l }, :class => 'btn btn-danger'

= bootstrap_form_for :tag, :url => tag_path(@tag), :html => {:method => 'put', :class => "form form-horizontal"} do |f|
  = f.text_field :name
  .controls
    = f.submit :update.l

app/views/tags/index.html.haml
-@page_title= :browse_content_by_tags.l

-widget do 
  %h3= :what_are_tags.l
  %p= :tags_are_one_word_descriptors_users_assign_to_blog_posts_pictures_and_clippings_on.l+" #{configatron.community_name}."
  %p= :bigger_font_size_more_popular_tag.l
    
-widget do 
  %h3= :search.l
  =form_tag search_tags_path, :method => 'get', :class => 'form' do
    .control-group
      .controls= text_field_tag 'id', params[:id], :autocomplete => "off", :placeholder => 'search tags'
    #id_auto_complete.auto_complete
    -content_for :end_javascript do
      = tag_auto_complete_field 'id', {:url => { :controller => "tags", :action => 'auto_complete_for_tag_name'}, :tokens => [','] }
    .controls
      = submit_tag :go.l, :class => 'btn btn-primary'

-tag_cloud @tags, %w(css1 css2 css3 css4 css5) do |tag, css_class|
  =link_to tag.name, tag_url(tag.to_param), :class => css_class

app/views/tags/manage.html.haml
-@page_title=:tags.l
= render :partial => 'shared/admin_nav'

-box do
  %h3=:search.l
  = bootstrap_form_for @search, :url => admin_tags_path, :html => {:class => "form form-horizontal"} do |f|
    = f.text_field :name_start, :label => :name.l

    .controls
      = f.submit :search.l

%table.table.table-bordered.table-striped
  %tr
    %th
      =sort_link @search, :name, :name.l
    %th
      =sort_link @search, :taggings_count, :taggings.l
    %th=:actions.l

  - for tag in @tags
    %tr
      %td= tag.name
      %td= tag.taggings.count
      %td
        = link_to :show.l, tag_path(tag), :class => 'btn'
        = link_to :edit.l, edit_tag_path(tag), :class => 'btn btn-warning'
        = link_to :destroy.l, tag_path(tag), data: { confirm: :are_you_sure.l }, :method => :delete, :class => 'btn btn-danger'

=paginate @tags, :theme => 'bootstrap'

app/views/tags/show.html.haml
-widget do 
  %ul.nav.nav-list
    %li.nav-header
      - if params[:type]
        = (params[:type].downcase.pluralize + '_tagged').l
      - else
        = :items_tagged.l
    - @tags.each do |tag|
      %li= link_to h(tag.name), tag_path(tag)
       
-if @related_tags.to_a.size > 0
  -widget do
    %h3=:related_tags.l
    -tag_cloud @related_tags, %w(css1 css2 css3 css4 css5) do |tag, css_class|
      =link_to h(tag.name), tag_path(tag), :class => css_class
    %p
      = icon_link_to 'icon-plus-sign', :all_tags.l, tags_path  

.clearfix    
  - if @posts.any?
    -unless params[:type]    
      %h2=:posts.l
      %ul
        - @posts.each do |post|
          %li
            = link_to( truncate(post.display_title, :length => 75), user_post_path(post.user, post), :title => :by.l(:login => post.user.login) )
            %p.post_excerpt= truncate_words(post.post, 35, '...' )
      = icon_link_to 'icon-plus-sign', :all_posts_tagged.l(:tag_name => @tags_raw), show_tag_type_path(:id => @tags_raw, :type => 'Post') unless params[:type]
    -else 
      = render :partial => 'posts/post', :collection => @posts      
      = paginate @posts, :theme => 'bootstrap'
      
.clearfix
  - if @photos.any?
    %h2=:photos.l(:count => @photos.size)
    %ul.thumbnails
      - @photos.each do |photo|
        %li.span3= link_to image_tag(photo.photo.url(:medium), :title => "#{photo.description} ("+:uploaded_by.l+" #{photo.user.login})"), user_photo_path(photo.user, photo), :class => "thumbnail"
    = icon_link_to 'icon-plus-sign', :all_photos_tagged.l(:tag_name => @tags_raw), show_tag_type_path(:id => @tags_raw, :type => 'Photo') unless params[:type]

.clearfix
  - if @users.any?
    %h2= t('tags.show.users')
    %ul.thumbnails
      - @users.each do |user|
        %li.span3= link_to image_tag(user.avatar_photo_url(:medium)), user_path(user), :title => user.login, :class => "thumbnail"
    = icon_link_to 'icon-plus-sign', :all_users_tagged.l(:tag_name => @tags_raw), show_tag_type_path(:id => @tags_raw, :type => 'User') unless params[:type]

.clearfix
  - unless @clippings.empty?
    %h2= :clippings.l
    %ul.thumbnails
      - @clippings.each do |clipping|
        %li.span3=render :partial => 'clippings/clipping', :locals => {:clipping => clipping}
    = icon_link_to 'icon-plus-sign', :all_clippings_tagged.l(:tag_name => @tags_raw), show_tag_type_path(:id => @tags_raw, :type => 'Clipping') unless params[:type]

- if @pages && !params[:type].eql?('Post')
  = paginate @pages, :theme => 'bootstrap'